onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp

packages:
  - "scripts/*"
  - "packages/*"

patchedDependencies:
  emf-converter@2.0.2: patches/emf-converter@2.0.2.patch
